#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace --exe top_control_mem_extend.sv cme_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop_control_mem_extend.mk Vtop_control_mem_extend

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vtop_control_mem_extend
echo "\nSimulation completed"

